def dia = new Date().getDay()
pipeline {
    agent any
    stages {
        stage('Lunes'){
            steps {
                script {
                   if(dia == 1)
                   println "--"
                }
            }
        }
        stage('Martes'){
            steps {
                script {
                   if(dia == 2)
                   println "--"
                }
            }
        }
        stage('Miercoles'){
            steps {
                script {
                   if(dia == 3)
                   println "--"
                }
            }
        }
        stage('Jueves'){
            steps {
                script {
                   if(dia == 4)
                   println "--"
                }
            }
        }
        stage('Viernes'){
            steps {
                script {
                   if(dia == 5){
                        def cause = currentBuild.rawBuild.getCause(Cause.UserIdCause)
                        if (cause != null) {
                            def user = cause.userId ?: 'anonymous'
                            println "La tarea está siendo ejecutada por: ${user}"
                        } else {
                            println "--"
                        } 
                   }
                }
            }
        }
    }
}